### ISSUE TITLE
Missing link in translated version

### ISSUE THREAD

**Issue by nanjoo-son** [NetAppDocs/active-iq#85] opened 2021-11-15 23:25 UTC
Page: [Execute Ansible Playbook using NetApp Docker image](https://docs.netapp.com/us-en/active-iq/task_execute_ansible_playbook_using_docker.html)

I found a missing link in Japanese translation and Chinese translation. English source content has two links but translated version has only one link.

![image](https://user-images.githubusercontent.com/94412138/141868234-df0a030e-450f-46f1-8b96-78c9d2602c21.png)

**Comment by netapp-gudugunti** [comment] 2021-11-16 04:51
Thanks! @nanjoo-son for bringing this to our attention.
Shall look into it and update you.

Regards,
Ashwath

**Comment by ggenzone** [comment] 2022-04-01 08:08
@nanjoo-son The problem is solved, thanks for letting us know.

![screenshot-docs netapp com-2022 04 01-09_51_45](https://user-images.githubusercontent.com/61072167/161221953-3e605d0a-ca71-40de-a65b-94eb641a3da4.png)

Japanese
![screenshot-docs netapp com-2022 04 01-10_07_40](https://user-images.githubusercontent.com/61072167/161222369-768d464d-fda4-4cf0-a5b2-76bb6d6fc883.png)

Chinese
![screenshot-docs netapp com-2022 04 01-10_02_52](https://user-images.githubusercontent.com/61072167/161222449-8e5b6b6c-37a0-4379-b906-5f332d393733.png)

**Comment by ntap-bmegan** [comment] 2022-08-23 21:00
Closing, dev issue is complete.

**Closed** 2022-08-30 13:34 UTC
