### ISSUE TITLE
Request to update the JA translation

### ISSUE THREAD

**Issue by taiganishimura-1129** [NetAppDocs/active-iq#72] opened 2021-07-20 00:54 UTC
Page: [法的通知](https://docs.netapp.com/ja-jp/active-iq/reference_legalnotices.html)

Please replace the JA translation "法的通知" with "知的財産権等について" for the title of this page.

**Comment by netapp-gudugunti** [comment] 2021-07-20 09:28
Duplicate of issue #71. I am not able to move the status to Closed.
@netapp-manishc could you help close this?

**Closed** 2021-07-20 09:34 UTC
